// File generated by FlutterFire CLI, or replaced in CI from FIREBASE_OPTIONS_DART secret.
// Do not commit real API keys. Local: run `flutterfire configure`. CI: workflow writes from secret.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  /// True when the current platform is using placeholder config (invalid for Auth). Run `flutterfire configure` for local sign-in.
  static bool get isPlaceholder {
    if (kIsWeb) return web.apiKey == 'REPLACE_VIA_FIREBASE_OPTIONS_DART';
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android.apiKey == 'REPLACE_VIA_FIREBASE_OPTIONS_DART';
      case TargetPlatform.iOS:
        return ios.apiKey == 'REPLACE_VIA_FIREBASE_OPTIONS_DART';
      default:
        return true;
    }
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Placeholder — replace in CI from FIREBASE_OPTIONS_DART or run `flutterfire configure` locally.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_VIA_FIREBASE_OPTIONS_DART',
    appId: '1:0:web:0',
    messagingSenderId: '0',
    projectId: 'your-project-id',
    authDomain: 'your-project-id.firebaseapp.com',
    storageBucket: 'your-project-id.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_VIA_FIREBASE_OPTIONS_DART',
    appId: '1:0:android:0',
    messagingSenderId: '0',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_VIA_FIREBASE_OPTIONS_DART',
    appId: '1:0:ios:0',
    messagingSenderId: '0',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.firebasestorage.app',
    iosBundleId: 'com.thomascortebeeck.waypoint',
  );

}