// File generated by FlutterFire CLI, or replaced in CI from FIREBASE_OPTIONS_DART secret.
// Do not commit real API keys. Local: run `flutterfire configure`. CI: workflow writes from secret.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  /// True when the current platform is using placeholder config (invalid for Auth). Run `flutterfire configure` for local sign-in.
  static bool get isPlaceholder {
    if (kIsWeb) return web.apiKey == 'REPLACE_VIA_FIREBASE_OPTIONS_DART';
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android.apiKey == 'REPLACE_VIA_FIREBASE_OPTIONS_DART';
      case TargetPlatform.iOS:
        return ios.apiKey == 'REPLACE_VIA_FIREBASE_OPTIONS_DART';
      default:
        return true;
    }
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPKS522n1bXPAdE9lVHecudziwll32Wl8',
    appId: '1:367031227804:web:0fc7dc8c51679700fa6459',
    messagingSenderId: '367031227804',
    projectId: 'lo72dwmjbzy4xz7nodczq859vs6xkf',
    authDomain: 'lo72dwmjbzy4xz7nodczq859vs6xkf.firebaseapp.com',
    storageBucket: 'lo72dwmjbzy4xz7nodczq859vs6xkf.firebasestorage.app',
  );

  /// Placeholder — replace in CI from FIREBASE_OPTIONS_DART or run `flutterfire configure` locally.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbA-EG6rvrBhgw5nK7vtDMIuu8RyEnwx0',
    appId: '1:367031227804:android:7d1e3c56e76de746fa6459',
    messagingSenderId: '367031227804',
    projectId: 'lo72dwmjbzy4xz7nodczq859vs6xkf',
    storageBucket: 'lo72dwmjbzy4xz7nodczq859vs6xkf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSE69rV2PcsGJ80b2R7AICD8UXcJ_nH0o',
    appId: '1:367031227804:ios:7ec3daeceb8d174bfa6459',
    messagingSenderId: '367031227804',
    projectId: 'lo72dwmjbzy4xz7nodczq859vs6xkf',
    storageBucket: 'lo72dwmjbzy4xz7nodczq859vs6xkf.firebasestorage.app',
    iosBundleId: 'com.thomascortebeeck.waypoint',
  );

}